// Mocks generated by Mockito 5.0.10 from annotations
// in lezato/test/restaurant_test.dart.
// Do not manually edit this file.

import 'package:lezato/data/api/api_service.dart' as _i3;
import 'package:lezato/provider/app_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [AppProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppProvider extends _i1.Mock implements _i2.AppProvider {
  MockAppProvider() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }
}
